### ISSUE TITLE
How can I check my current training status?

### ISSUE THREAD

**Issue by km23630** [zeppaman/KerasUI#5]
after click training button, i can't found stop training button also i can't check my training status.
Is the only way to stop training is to shut down the console?
or is there another way?

**Comment by zeppaman** [comment]
Hi @km23630,  atm the only way to stop it is to kill the application. 
As a future implementation, I plan to keep progress field updated (there is a progress field but it is set only after the end, so it is basically 0% until the end) and a second action, similar to the train one that kills the background thread without shutting down all.
Moreover, as suggested by @girardengo, read the console output from the web UI will be a great improvement.

**Comment by zeppaman** [comment]
About the progress, I committed a small changes to keep progress update. It works using keras kallback and, after each batch is completed, updates the progress.

For the termination, because is not possible easily to kill the thread, I want to use a kera callback like the EarlyStop, but activated by some flag on dataset row. This will allow also some "soft" stop.

**Comment by km23630** [comment]
> About the progress, I committed a small changes to keep progress update. It works using keras kallback and, after each batch is completed, updates the progress.
> 
> For the termination, because is not possible easily to kill the thread, I want to use a kera callback like the EarlyStop, but activated by some flag on dataset row. This will allow also some "soft" stop.

thank you~
